/*******************************************************************************
 * Object Type: Trigger
 * Schema: ACE
 * Name: trgAutoGen_MasterFileAccounts_CUD
 * Description: Autogenerated trigger to audit CUD operations for ACE.MasterFileAccounts.
 *              Fires AFTER INSERT, UPDATE. Captures old/new column values and
 *              writes audit records to AUD.AuditActions and AUD.AuditActionColumns.
 * Dependencies: ACC.fxGetContextUserTable, AUD.AuditActions, AUD.AuditActionColumns
 * Author: Andres E. Sosa
 * Created: 2017-09-27
 ******************************************************************************/

IF OBJECT_ID('[ACE].[trgAutoGen_MasterFileAccounts_CUD]', 'TR') IS NOT NULL
    DROP TRIGGER [ACE].[trgAutoGen_MasterFileAccounts_CUD];
GO

CREATE TRIGGER [ACE].[trgAutoGen_MasterFileAccounts_CUD] ON [ACE].[MasterFileAccounts]
	AFTER INSERT, UPDATE
AS
BEGIN
    /**************
	 * INITIALIZE
	 **************/
    DECLARE @UserID UNIQUEIDENTIFIER, @UserGuidMasked VARCHAR(50), @DealerId INT;
    SELECT @UserID = UserID, @UserGuidMasked = UserGuidMasked, @DealerId = DealerId
    FROM [ACC].[fxGetContextUserTable]();
    DECLARE @DeletedTable TABLE (PKID VARCHAR(50) NOT NULL);
    INSERT INTO @DeletedTable
        ( PKID )
    SELECT MasterFileAccountID
    FROM Deleted;

    /** Build Data Changes */
    DECLARE @DataTable TABLE (PKID VARCHAR(50) NOT NULL,
        AuditActionId BIGINT,
        AuditActionTypeId VARCHAR(20),
        ColumnName NVARCHAR(500),
        OldValue NVARCHAR(500),
        NewValue NVARCHAR(500));
    WITH
        RootCTE
        AS
        (
            SELECT
                PKID, InsertValues.ColumnName, InsertValues.ColumnNewValue
            FROM
                (SELECT
                    MFD.MasterFileAccountID AS PKID
			, CAST(MasterFileAccountID AS NVARCHAR(500)) AS MasterFileAccountID
			, CAST(MasterFileId AS NVARCHAR(500)) AS MasterFileId
			, CAST(DealerId AS NVARCHAR(500)) AS DealerId
			, CAST(CustomerTypeId AS NVARCHAR(500)) AS CustomerTypeId
			, CAST(LeadId AS NVARCHAR(500)) AS LeadId
			, CAST(Lead2Id AS NVARCHAR(500)) AS Lead2Id
			, CAST(AccountId AS NVARCHAR(500)) AS AccountId
			, CAST(AccountTypeId AS NVARCHAR(500)) AS AccountTypeId
			, CAST(CustomerId AS NVARCHAR(500)) AS CustomerId
			, CAST(Customer2Id AS NVARCHAR(500)) AS Customer2Id
			, CAST(MonthlyContractId AS NVARCHAR(500)) AS MonthlyContractId
			, CAST(InstallFeeContractId AS NVARCHAR(500)) AS InstallFeeContractId
			, CAST(BillingDay AS NVARCHAR(500)) AS BillingDay
			, CAST(EffectiveDate AS NVARCHAR(500)) AS EffectiveDate
			, CAST(ContractLockDate AS NVARCHAR(500)) AS ContractLockDate
			, CAST(IsActive AS NVARCHAR(500)) AS IsActive
			, CAST(IsDeleted AS NVARCHAR(500)) AS IsDeleted
                FROM
                    Inserted AS MFD WITH(NOLOCK)) AS st2
		UNPIVOT (
			ColumnNewValue FOR ColumnName IN (
			MasterFileAccountID
			, MasterFileId
			, DealerId
			, CustomerTypeId
			, LeadId
			, Lead2Id
			, AccountId
			, AccountTypeId
			, CustomerId
			, Customer2Id
			, MonthlyContractId
			, InstallFeeContractId
			, BillingDay
			, EffectiveDate
			, ContractLockDate
			, IsActive
			, IsDeleted
			)
		) AS InsertValues
        )
	,
        WithChangedCTE
        AS
        (
            SELECT
                PKID
			, InsertValues.ColumnName
			, InsertValues.ColumnOldValue
            FROM
                (SELECT
                    MFD.MasterFileAccountID AS PKID
			, CAST(MasterFileAccountID AS NVARCHAR(500)) AS MasterFileAccountID
			, CAST(MasterFileId AS NVARCHAR(500)) AS MasterFileId
			, CAST(DealerId AS NVARCHAR(500)) AS DealerId
			, CAST(CustomerTypeId AS NVARCHAR(500)) AS CustomerTypeId
			, CAST(LeadId AS NVARCHAR(500)) AS LeadId
			, CAST(Lead2Id AS NVARCHAR(500)) AS Lead2Id
			, CAST(AccountId AS NVARCHAR(500)) AS AccountId
			, CAST(AccountTypeId AS NVARCHAR(500)) AS AccountTypeId
			, CAST(CustomerId AS NVARCHAR(500)) AS CustomerId
			, CAST(Customer2Id AS NVARCHAR(500)) AS Customer2Id
			, CAST(MonthlyContractId AS NVARCHAR(500)) AS MonthlyContractId
			, CAST(InstallFeeContractId AS NVARCHAR(500)) AS InstallFeeContractId
			, CAST(BillingDay AS NVARCHAR(500)) AS BillingDay
			, CAST(EffectiveDate AS NVARCHAR(500)) AS EffectiveDate
			, CAST(ContractLockDate AS NVARCHAR(500)) AS ContractLockDate
			, CAST(IsActive AS NVARCHAR(500)) AS IsActive
			, CAST(IsDeleted AS NVARCHAR(500)) AS IsDeleted
                FROM
                    Deleted AS MFD) AS st2
		UNPIVOT (
			ColumnOldValue FOR ColumnName IN (
			MasterFileAccountID
			, MasterFileId
			, DealerId
			, CustomerTypeId
			, LeadId
			, Lead2Id
			, AccountId
			, AccountTypeId
			, CustomerId
			, Customer2Id
			, MonthlyContractId
			, InstallFeeContractId
			, BillingDay
			, EffectiveDate
			, ContractLockDate
			, IsActive
			, IsDeleted
			)
		) AS InsertValues
        )
	,
        ResultCTE
        AS
        (
            SELECT
                RTN.PKID
			, RTN.ColumnName
			, RTN.ColumnNewValue AS NewValue
			, RTO.ColumnOldValue AS OldValue
            FROM
                RootCTE AS RTN WITH(NOLOCK)
                LEFT OUTER JOIN WithChangedCTE AS RTO WITH(NOLOCK)
                ON
				(RTO.PKID = RTN.PKID)
                    AND (RTO.ColumnName = RTN.ColumnName)
            WHERE
			(RTO.ColumnOldValue IS NULL OR RTN.ColumnNewValue <> RTO.ColumnOldValue)
        )
    INSERT INTO @DataTable
        (PKID, ColumnName, OldValue, NewValue)
    SELECT
        RT.PKID
        , RT.ColumnName
        , RT.OldValue
        , RT.NewValue
    FROM
        ResultCTE AS RT WITH(NOLOCK);

    /** Determin Action */
    WITH
        DistinctCTE
        AS
        (
            SELECT DISTINCT
                RT.PKID
            FROM
                @DataTable AS RT
        )
	,
        DeletedActionCTE
        AS
        (
            SELECT
                RT.PKID
			, (SELECT CAST('True' AS BIT)
                FROM @DataTable
                WHERE PKID = RT.PKID AND ColumnName = 'IsDeleted' AND NewValue = '1') AS IsDeleteAction
			, (SELECT CAST('True' AS BIT)
                FROM @DataTable
                WHERE PKID = RT.PKID AND ColumnName = 'IsDeleted' AND NewValue = '0' AND OldValue = '1') AS IsUnDeleteAction
			, CASE
				WHEN DT.PKID IS NULL THEN CAST('False' AS BIT)
				ELSE CAST('True' AS BIT)
			  END AS IsUpdateAction
            FROM
                DistinctCTE AS RT
                LEFT OUTER JOIN @DeletedTable AS DT
                ON
				(DT.PKID = RT.PKID)
        )
	,
        DetermineActionTypeCTE
        AS
        (
            SELECT
                DT.PKID
			, CASE
				WHEN DACT.IsDeleteAction = 'True' THEN 'DELETE'
				WHEN DACT.IsUnDeleteAction = 'True' THEN 'UNDELETE'
				WHEN DACT.IsUpdateAction = 'True' THEN 'UPDATE'
				ELSE 'INSERT'
			  END AS AuditActionTypeId
            FROM
                @DataTable AS DT
                LEFT OUTER JOIN DeletedActionCTE AS DACT WITH(NOLOCK)
                ON
				(DACT.PKID = DT.PKID)
        )
	UPDATE DT SET
		DT.AuditActionTypeId = DACT.AuditActionTypeId
	FROM
        @DataTable AS DT
        INNER JOIN DetermineActionTypeCTE AS DACT WITH(NOLOCK)
        ON
			(DACT.PKID = DT.PKID);

    /** CREATE THE AUDIT ACTIONS */
    DECLARE @AuditActionTable TABLE (AuditActionID BIGINT,
        PKID VARCHAR(50));
    INSERT INTO [AUD].[AuditActions]
        ([AuditActionTypeId], [SchemaName], [TableName], [PrimaryKeyIdentifier], [CreatedById])
    OUTPUT INSERTED.AuditActionID, INSERTED.PrimaryKeyIdentifier INTO @AuditActionTable
    SELECT DISTINCT
        DT.AuditActionTypeId
		, 'ACE'
		, 'MasterFileAccounts'
		, CAST(DT.PKID AS VARCHAR(50))
		, @UserID
    FROM
        @DataTable AS DT;

    /** CREATE THE AUDIT ACTION COLUMNS */
    INSERT INTO [AUD].[AuditActionColumns]
        ([AuditActionId], [ColumnName], [OldValue], [NewValue])
    SELECT DISTINCT
        AAT.AuditActionID
		, DT.ColumnName
		, DT.OldValue
		, DT.NewValue
    FROM
        @DataTable AS DT
        INNER JOIN @AuditActionTable AS AAT
        ON
			(AAT.PKID = DT.PKID)
END;
GO
