/*******************************************************************************
 * Object Type: Trigger
 * Schema: ACE
 * Name: trgAutoGen_Customers_CUD
 * Description: Autogenerated trigger to audit CUD operations for ACE.Customers.
 *              Fires AFTER INSERT, UPDATE. Captures old/new column values and
 *              writes audit records to AUD.AuditActions and AUD.AuditActionColumns.
 * Dependencies: ACC.fxGetContextUserTable, AUD.AuditActions, AUD.AuditActionColumns
 * Author: Andres E. Sosa
 * Created: 2017-09-27
 ******************************************************************************/

IF OBJECT_ID('[ACE].[trgAutoGen_Customers_CUD]', 'TR') IS NOT NULL
    DROP TRIGGER [ACE].[trgAutoGen_Customers_CUD];
GO

CREATE TRIGGER [ACE].[trgAutoGen_Customers_CUD] ON [ACE].[Customers]
	AFTER INSERT, UPDATE
AS
BEGIN
    /**************
	 * INITIALIZE
	 **************/
    DECLARE @UserID UNIQUEIDENTIFIER, @UserGuidMasked VARCHAR(50), @DealerId INT;
    SELECT @UserID = UserID, @UserGuidMasked = UserGuidMasked, @DealerId = DealerId
    FROM [ACC].[fxGetContextUserTable]();
    DECLARE @DeletedTable TABLE (PKID BIGINT NOT NULL);
    INSERT INTO @DeletedTable
        ( PKID )
    SELECT CustomerID
    FROM Deleted;

    /** Build Data Changes */
    DECLARE @DataTable TABLE (PKID BIGINT NOT NULL,
        AuditActionId BIGINT,
        AuditActionTypeId VARCHAR(20),
        ColumnName NVARCHAR(500),
        OldValue NVARCHAR(500),
        NewValue NVARCHAR(500));
    WITH
        RootCTE
        AS
        (
            SELECT
                PKID, InsertValues.ColumnName, InsertValues.ColumnNewValue
            FROM
                (SELECT
                    MFD.CustomerID AS PKID
			, CAST(CustomerID AS NVARCHAR(500)) AS CustomerID
			, CAST(CustomerTypeId AS NVARCHAR(500)) AS CustomerTypeId
			, CAST(MasterFileId AS NVARCHAR(500)) AS MasterFileId
			, CAST(DealerId AS NVARCHAR(500)) AS DealerId
			, CAST(CustomerAddressId AS NVARCHAR(500)) AS CustomerAddressId
			, CAST(LeadId AS NVARCHAR(500)) AS LeadId
			, CAST(LanguageId AS NVARCHAR(500)) AS LanguageId
			, CAST(Prefix AS NVARCHAR(500)) AS Prefix
			, CAST(FirstName AS NVARCHAR(500)) AS FirstName
			, CAST(MiddleName AS NVARCHAR(500)) AS MiddleName
			, CAST(LastName AS NVARCHAR(500)) AS LastName
			, CAST(Postfix AS NVARCHAR(500)) AS Postfix
			, CAST(BusinessName AS NVARCHAR(500)) AS BusinessName
			, CAST(Gender AS NVARCHAR(500)) AS Gender
			, CAST(PhoneHome AS NVARCHAR(500)) AS PhoneHome
			, CAST(PhoneWork AS NVARCHAR(500)) AS PhoneWork
			, CAST(PhoneMobile AS NVARCHAR(500)) AS PhoneMobile
			, CAST(Email AS NVARCHAR(500)) AS Email
			, CAST(DOB AS NVARCHAR(500)) AS DOB
			, CAST(SSN AS NVARCHAR(500)) AS SSN
			, CAST(Username AS NVARCHAR(500)) AS Username
			, CAST(Password AS NVARCHAR(500)) AS Password
			, CAST(IsActive AS NVARCHAR(500)) AS IsActive
			, CAST(IsDeleted AS NVARCHAR(500)) AS IsDeleted
                FROM
                    Inserted AS MFD WITH(NOLOCK)) AS st2
		UNPIVOT (
			ColumnNewValue FOR ColumnName IN (
			CustomerID
			, CustomerTypeId
			, MasterFileId
			, DealerId
			, CustomerAddressId
			, LeadId
			, LanguageId
			, Prefix
			, FirstName
			, MiddleName
			, LastName
			, Postfix
			, BusinessName
			, Gender
			, PhoneHome
			, PhoneWork
			, PhoneMobile
			, Email
			, DOB
			, SSN
			, Username
			, Password
			, IsActive
			, IsDeleted
			)
		) AS InsertValues
        )
	,
        WithChangedCTE
        AS
        (
            SELECT
                PKID
			, InsertValues.ColumnName
			, InsertValues.ColumnOldValue
            FROM
                (SELECT
                    MFD.CustomerID AS PKID
			, CAST(CustomerID AS NVARCHAR(500)) AS CustomerID
			, CAST(CustomerTypeId AS NVARCHAR(500)) AS CustomerTypeId
			, CAST(MasterFileId AS NVARCHAR(500)) AS MasterFileId
			, CAST(DealerId AS NVARCHAR(500)) AS DealerId
			, CAST(CustomerAddressId AS NVARCHAR(500)) AS CustomerAddressId
			, CAST(LeadId AS NVARCHAR(500)) AS LeadId
			, CAST(LanguageId AS NVARCHAR(500)) AS LanguageId
			, CAST(Prefix AS NVARCHAR(500)) AS Prefix
			, CAST(FirstName AS NVARCHAR(500)) AS FirstName
			, CAST(MiddleName AS NVARCHAR(500)) AS MiddleName
			, CAST(LastName AS NVARCHAR(500)) AS LastName
			, CAST(Postfix AS NVARCHAR(500)) AS Postfix
			, CAST(BusinessName AS NVARCHAR(500)) AS BusinessName
			, CAST(Gender AS NVARCHAR(500)) AS Gender
			, CAST(PhoneHome AS NVARCHAR(500)) AS PhoneHome
			, CAST(PhoneWork AS NVARCHAR(500)) AS PhoneWork
			, CAST(PhoneMobile AS NVARCHAR(500)) AS PhoneMobile
			, CAST(Email AS NVARCHAR(500)) AS Email
			, CAST(DOB AS NVARCHAR(500)) AS DOB
			, CAST(SSN AS NVARCHAR(500)) AS SSN
			, CAST(Username AS NVARCHAR(500)) AS Username
			, CAST(Password AS NVARCHAR(500)) AS Password
			, CAST(IsActive AS NVARCHAR(500)) AS IsActive
			, CAST(IsDeleted AS NVARCHAR(500)) AS IsDeleted
                FROM
                    Deleted AS MFD) AS st2
		UNPIVOT (
			ColumnOldValue FOR ColumnName IN (
			CustomerID
			, CustomerTypeId
			, MasterFileId
			, DealerId
			, CustomerAddressId
			, LeadId
			, LanguageId
			, Prefix
			, FirstName
			, MiddleName
			, LastName
			, Postfix
			, BusinessName
			, Gender
			, PhoneHome
			, PhoneWork
			, PhoneMobile
			, Email
			, DOB
			, SSN
			, Username
			, Password
			, IsActive
			, IsDeleted
			)
		) AS InsertValues
        )
	,
        ResultCTE
        AS
        (
            SELECT
                RTN.PKID
			, RTN.ColumnName
			, RTN.ColumnNewValue AS NewValue
			, RTO.ColumnOldValue AS OldValue
            FROM
                RootCTE AS RTN WITH(NOLOCK)
                LEFT OUTER JOIN WithChangedCTE AS RTO WITH(NOLOCK)
                ON
				(RTO.PKID = RTN.PKID)
                    AND (RTO.ColumnName = RTN.ColumnName)
            WHERE
			(RTO.ColumnOldValue IS NULL OR RTN.ColumnNewValue <> RTO.ColumnOldValue)
        )
    INSERT INTO @DataTable
        (PKID, ColumnName, OldValue, NewValue)
    SELECT
        RT.PKID
        , RT.ColumnName
        , RT.OldValue
        , RT.NewValue
    FROM
        ResultCTE AS RT WITH(NOLOCK);

    /** Determin Action */
    WITH
        DistinctCTE
        AS
        (
            SELECT DISTINCT
                RT.PKID
            FROM
                @DataTable AS RT
        )
	,
        DeletedActionCTE
        AS
        (
            SELECT
                RT.PKID
			, (SELECT CAST('True' AS BIT)
                FROM @DataTable
                WHERE PKID = RT.PKID AND ColumnName = 'IsDeleted' AND NewValue = '1') AS IsDeleteAction
			, (SELECT CAST('True' AS BIT)
                FROM @DataTable
                WHERE PKID = RT.PKID AND ColumnName = 'IsDeleted' AND NewValue = '0' AND OldValue = '1') AS IsUnDeleteAction
			, CASE
				WHEN DT.PKID IS NULL THEN CAST('False' AS BIT)
				ELSE CAST('True' AS BIT)
			  END AS IsUpdateAction
            FROM
                DistinctCTE AS RT
                LEFT OUTER JOIN @DeletedTable AS DT
                ON
				(DT.PKID = RT.PKID)
        )
	,
        DetermineActionTypeCTE
        AS
        (
            SELECT
                DT.PKID
			, CASE
				WHEN DACT.IsDeleteAction = 'True' THEN 'DELETE'
				WHEN DACT.IsUnDeleteAction = 'True' THEN 'UNDELETE'
				WHEN DACT.IsUpdateAction = 'True' THEN 'UPDATE'
				ELSE 'INSERT'
			  END AS AuditActionTypeId
            FROM
                @DataTable AS DT
                LEFT OUTER JOIN DeletedActionCTE AS DACT WITH(NOLOCK)
                ON
				(DACT.PKID = DT.PKID)
        )
	UPDATE DT SET
		DT.AuditActionTypeId = DACT.AuditActionTypeId
	FROM
        @DataTable AS DT
        INNER JOIN DetermineActionTypeCTE AS DACT WITH(NOLOCK)
        ON
			(DACT.PKID = DT.PKID);

    /** CREATE THE AUDIT ACTIONS */
    DECLARE @AuditActionTable TABLE (AuditActionID BIGINT,
        PKID VARCHAR(50));
    INSERT INTO [AUD].[AuditActions]
        ([AuditActionTypeId], [SchemaName], [TableName], [PrimaryKeyIdentifier], [CreatedById])
    OUTPUT INSERTED.AuditActionID, INSERTED.PrimaryKeyIdentifier INTO @AuditActionTable
    SELECT DISTINCT
        DT.AuditActionTypeId
		, 'ACE'
		, 'Customers'
		, CAST(DT.PKID AS VARCHAR(50))
		, @UserID
    FROM
        @DataTable AS DT;

    /** CREATE THE AUDIT ACTION COLUMNS */
    INSERT INTO [AUD].[AuditActionColumns]
        ([AuditActionId], [ColumnName], [OldValue], [NewValue])
    SELECT DISTINCT
        AAT.AuditActionID
		, DT.ColumnName
		, DT.OldValue
		, DT.NewValue
    FROM
        @DataTable AS DT
        INNER JOIN @AuditActionTable AS AAT
        ON
			(AAT.PKID = DT.PKID)
END;
GO
