/*******************************************************************************
 * Object Type: Trigger
 * Schema: QAL
 * Name: trgAutoGen_LeadAddresses_CUD
 * Description: Autogenerated trigger to audit CUD operations for QAL.LeadAddresses.
 *              Fires AFTER INSERT, UPDATE. Captures old/new column values and
 *              writes audit records to AUD.AuditActions and AUD.AuditActionColumns.
 * Dependencies: ACC.fxGetContextUserTable, AUD.AuditActions, AUD.AuditActionColumns
 * Author: Andres E. Sosa
 * Created: 2017-09-27
 ******************************************************************************/

IF OBJECT_ID('[QAL].[trgAutoGen_LeadAddresses_CUD]', 'TR') IS NOT NULL
    DROP TRIGGER [QAL].[trgAutoGen_LeadAddresses_CUD];
GO

CREATE TRIGGER [QAL].[trgAutoGen_LeadAddresses_CUD] ON [QAL].[LeadAddresses]
	AFTER INSERT, UPDATE
AS
BEGIN
    /**************
	 * INITIALIZE
	 **************/
    DECLARE @UserID UNIQUEIDENTIFIER, @UserGuidMasked VARCHAR(50), @DealerId INT;
    SELECT @UserID = UserID, @UserGuidMasked = UserGuidMasked, @DealerId = DealerId
    FROM [ACC].[fxGetContextUserTable]();
    DECLARE @DeletedTable TABLE (PKID BIGINT NOT NULL);
    INSERT INTO @DeletedTable
        ( PKID )
    SELECT LeadAddressID
    FROM Deleted;

    /** Build Data Changes */
    DECLARE @DataTable TABLE (PKID BIGINT NOT NULL,
        AuditActionId BIGINT,
        AuditActionTypeId VARCHAR(20),
        ColumnName NVARCHAR(500),
        OldValue NVARCHAR(500),
        NewValue NVARCHAR(500));
    WITH
        RootCTE
        AS
        (
            SELECT
                PKID, InsertValues.ColumnName, InsertValues.ColumnNewValue
            FROM
                (SELECT
                    MFD.LeadAddressID AS PKID
			, CAST(LeadAddressID AS NVARCHAR(500)) AS LeadAddressID
			, CAST(DealerId AS NVARCHAR(500)) AS DealerId
			, CAST(LanguageId AS NVARCHAR(500)) AS LanguageId
			, CAST(AddressValidationVendorId AS NVARCHAR(500)) AS AddressValidationVendorId
			, CAST(AddressValidationStateId AS NVARCHAR(500)) AS AddressValidationStateId
			, CAST(PoliticalStateId AS NVARCHAR(500)) AS PoliticalStateId
			, CAST(PoliticalCountryId AS NVARCHAR(500)) AS PoliticalCountryId
			, CAST(PoliticalTimeZoneId AS NVARCHAR(500)) AS PoliticalTimeZoneId
			, CAST(AddressTypeId AS NVARCHAR(500)) AS AddressTypeId
			, CAST(AddressStreetTypeId AS NVARCHAR(500)) AS AddressStreetTypeId
			, CAST(SeasonId AS NVARCHAR(500)) AS SeasonId
			, CAST(TeamLocationId AS NVARCHAR(500)) AS TeamLocationId
			, CAST(SalesRepId AS NVARCHAR(500)) AS SalesRepId
			, CAST(StreetAddress AS NVARCHAR(500)) AS StreetAddress
			, CAST(StreetAddress2 AS NVARCHAR(500)) AS StreetAddress2
			, CAST(StreetNumber AS NVARCHAR(500)) AS StreetNumber
			, CAST(StreetName AS NVARCHAR(500)) AS StreetName
			, CAST(StreetType AS NVARCHAR(500)) AS StreetType
			, CAST(PreDirectional AS NVARCHAR(500)) AS PreDirectional
			, CAST(PostDirectional AS NVARCHAR(500)) AS PostDirectional
			, CAST(Extension AS NVARCHAR(500)) AS Extension
			, CAST(ExtensionNumber AS NVARCHAR(500)) AS ExtensionNumber
			, CAST(County AS NVARCHAR(500)) AS County
			, CAST(CountyCode AS NVARCHAR(500)) AS CountyCode
			, CAST(Urbanization AS NVARCHAR(500)) AS Urbanization
			, CAST(UrbanizationCode AS NVARCHAR(500)) AS UrbanizationCode
			, CAST(City AS NVARCHAR(500)) AS City
			, CAST(PostalCode AS NVARCHAR(500)) AS PostalCode
			, CAST(PlusFour AS NVARCHAR(500)) AS PlusFour
			, CAST(PostalCodeFull AS NVARCHAR(500)) AS PostalCodeFull
			, CAST(Phone AS NVARCHAR(500)) AS Phone
			, CAST(DeliveryPoint AS NVARCHAR(500)) AS DeliveryPoint
			, CAST(CrossStreet AS NVARCHAR(500)) AS CrossStreet
			, CAST(Latitude AS NVARCHAR(500)) AS Latitude
			, CAST(Longitude AS NVARCHAR(500)) AS Longitude
			, CAST(CongressionalDistric AS NVARCHAR(500)) AS CongressionalDistric
			, CAST(DPV AS NVARCHAR(500)) AS DPV
			, CAST(DPVResponse AS NVARCHAR(500)) AS DPVResponse
			, CAST(DPVFootnote AS NVARCHAR(500)) AS DPVFootnote
			, CAST(CarrierRoute AS NVARCHAR(500)) AS CarrierRoute
			, CAST(IsActive AS NVARCHAR(500)) AS IsActive
			, CAST(IsDeleted AS NVARCHAR(500)) AS IsDeleted
                FROM
                    Inserted AS MFD WITH(NOLOCK)) AS st2
		UNPIVOT (
			ColumnNewValue FOR ColumnName IN (
			LeadAddressID
			, DealerId
			, LanguageId
			, AddressValidationVendorId
			, AddressValidationStateId
			, PoliticalStateId
			, PoliticalCountryId
			, PoliticalTimeZoneId
			, AddressTypeId
			, AddressStreetTypeId
			, SeasonId
			, TeamLocationId
			, SalesRepId
			, StreetAddress
			, StreetAddress2
			, StreetNumber
			, StreetName
			, StreetType
			, PreDirectional
			, PostDirectional
			, Extension
			, ExtensionNumber
			, County
			, CountyCode
			, Urbanization
			, UrbanizationCode
			, City
			, PostalCode
			, PlusFour
			, PostalCodeFull
			, Phone
			, DeliveryPoint
			, CrossStreet
			, Latitude
			, Longitude
			, CongressionalDistric
			, DPV
			, DPVResponse
			, DPVFootnote
			, CarrierRoute
			, IsActive
			, IsDeleted
			)
		) AS InsertValues
        )
	,
        WithChangedCTE
        AS
        (
            SELECT
                PKID
			, InsertValues.ColumnName
			, InsertValues.ColumnOldValue
            FROM
                (SELECT
                    MFD.LeadAddressID AS PKID
			, CAST(LeadAddressID AS NVARCHAR(500)) AS LeadAddressID
			, CAST(DealerId AS NVARCHAR(500)) AS DealerId
			, CAST(LanguageId AS NVARCHAR(500)) AS LanguageId
			, CAST(AddressValidationVendorId AS NVARCHAR(500)) AS AddressValidationVendorId
			, CAST(AddressValidationStateId AS NVARCHAR(500)) AS AddressValidationStateId
			, CAST(PoliticalStateId AS NVARCHAR(500)) AS PoliticalStateId
			, CAST(PoliticalCountryId AS NVARCHAR(500)) AS PoliticalCountryId
			, CAST(PoliticalTimeZoneId AS NVARCHAR(500)) AS PoliticalTimeZoneId
			, CAST(AddressTypeId AS NVARCHAR(500)) AS AddressTypeId
			, CAST(AddressStreetTypeId AS NVARCHAR(500)) AS AddressStreetTypeId
			, CAST(SeasonId AS NVARCHAR(500)) AS SeasonId
			, CAST(TeamLocationId AS NVARCHAR(500)) AS TeamLocationId
			, CAST(SalesRepId AS NVARCHAR(500)) AS SalesRepId
			, CAST(StreetAddress AS NVARCHAR(500)) AS StreetAddress
			, CAST(StreetAddress2 AS NVARCHAR(500)) AS StreetAddress2
			, CAST(StreetNumber AS NVARCHAR(500)) AS StreetNumber
			, CAST(StreetName AS NVARCHAR(500)) AS StreetName
			, CAST(StreetType AS NVARCHAR(500)) AS StreetType
			, CAST(PreDirectional AS NVARCHAR(500)) AS PreDirectional
			, CAST(PostDirectional AS NVARCHAR(500)) AS PostDirectional
			, CAST(Extension AS NVARCHAR(500)) AS Extension
			, CAST(ExtensionNumber AS NVARCHAR(500)) AS ExtensionNumber
			, CAST(County AS NVARCHAR(500)) AS County
			, CAST(CountyCode AS NVARCHAR(500)) AS CountyCode
			, CAST(Urbanization AS NVARCHAR(500)) AS Urbanization
			, CAST(UrbanizationCode AS NVARCHAR(500)) AS UrbanizationCode
			, CAST(City AS NVARCHAR(500)) AS City
			, CAST(PostalCode AS NVARCHAR(500)) AS PostalCode
			, CAST(PlusFour AS NVARCHAR(500)) AS PlusFour
			, CAST(PostalCodeFull AS NVARCHAR(500)) AS PostalCodeFull
			, CAST(Phone AS NVARCHAR(500)) AS Phone
			, CAST(DeliveryPoint AS NVARCHAR(500)) AS DeliveryPoint
			, CAST(CrossStreet AS NVARCHAR(500)) AS CrossStreet
			, CAST(Latitude AS NVARCHAR(500)) AS Latitude
			, CAST(Longitude AS NVARCHAR(500)) AS Longitude
			, CAST(CongressionalDistric AS NVARCHAR(500)) AS CongressionalDistric
			, CAST(DPV AS NVARCHAR(500)) AS DPV
			, CAST(DPVResponse AS NVARCHAR(500)) AS DPVResponse
			, CAST(DPVFootnote AS NVARCHAR(500)) AS DPVFootnote
			, CAST(CarrierRoute AS NVARCHAR(500)) AS CarrierRoute
			, CAST(IsActive AS NVARCHAR(500)) AS IsActive
			, CAST(IsDeleted AS NVARCHAR(500)) AS IsDeleted
                FROM
                    Deleted AS MFD) AS st2
		UNPIVOT (
			ColumnOldValue FOR ColumnName IN (
			LeadAddressID
			, DealerId
			, LanguageId
			, AddressValidationVendorId
			, AddressValidationStateId
			, PoliticalStateId
			, PoliticalCountryId
			, PoliticalTimeZoneId
			, AddressTypeId
			, AddressStreetTypeId
			, SeasonId
			, TeamLocationId
			, SalesRepId
			, StreetAddress
			, StreetAddress2
			, StreetNumber
			, StreetName
			, StreetType
			, PreDirectional
			, PostDirectional
			, Extension
			, ExtensionNumber
			, County
			, CountyCode
			, Urbanization
			, UrbanizationCode
			, City
			, PostalCode
			, PlusFour
			, PostalCodeFull
			, Phone
			, DeliveryPoint
			, CrossStreet
			, Latitude
			, Longitude
			, CongressionalDistric
			, DPV
			, DPVResponse
			, DPVFootnote
			, CarrierRoute
			, IsActive
			, IsDeleted
			)
		) AS InsertValues
        )
	,
        ResultCTE
        AS
        (
            SELECT
                RTN.PKID
			, RTN.ColumnName
			, RTN.ColumnNewValue AS NewValue
			, RTO.ColumnOldValue AS OldValue
            FROM
                RootCTE AS RTN WITH(NOLOCK)
                LEFT OUTER JOIN WithChangedCTE AS RTO WITH(NOLOCK)
                ON
				(RTO.PKID = RTN.PKID)
                    AND (RTO.ColumnName = RTN.ColumnName)
            WHERE
			(RTO.ColumnOldValue IS NULL OR RTN.ColumnNewValue <> RTO.ColumnOldValue)
        )
    INSERT INTO @DataTable
        (PKID, ColumnName, OldValue, NewValue)
    SELECT
        RT.PKID
        , RT.ColumnName
        , RT.OldValue
        , RT.NewValue
    FROM
        ResultCTE AS RT WITH(NOLOCK);

    /** Determin Action */
    WITH
        DistinctCTE
        AS
        (
            SELECT DISTINCT
                RT.PKID
            FROM
                @DataTable AS RT
        )
	,
        DeletedActionCTE
        AS
        (
            SELECT
                RT.PKID
			, (SELECT CAST('True' AS BIT)
                FROM @DataTable
                WHERE PKID = RT.PKID AND ColumnName = 'IsDeleted' AND NewValue = '1') AS IsDeleteAction
			, (SELECT CAST('True' AS BIT)
                FROM @DataTable
                WHERE PKID = RT.PKID AND ColumnName = 'IsDeleted' AND NewValue = '0' AND OldValue = '1') AS IsUnDeleteAction
			, CASE
				WHEN DT.PKID IS NULL THEN CAST('False' AS BIT)
				ELSE CAST('True' AS BIT)
			  END AS IsUpdateAction
            FROM
                DistinctCTE AS RT
                LEFT OUTER JOIN @DeletedTable AS DT
                ON
				(DT.PKID = RT.PKID)
        )
	,
        DetermineActionTypeCTE
        AS
        (
            SELECT
                DT.PKID
			, CASE
				WHEN DACT.IsDeleteAction = 'True' THEN 'DELETE'
				WHEN DACT.IsUnDeleteAction = 'True' THEN 'UNDELETE'
				WHEN DACT.IsUpdateAction = 'True' THEN 'UPDATE'
				ELSE 'INSERT'
			  END AS AuditActionTypeId
            FROM
                @DataTable AS DT
                LEFT OUTER JOIN DeletedActionCTE AS DACT WITH(NOLOCK)
                ON
				(DACT.PKID = DT.PKID)
        )
	UPDATE DT SET
		DT.AuditActionTypeId = DACT.AuditActionTypeId
	FROM
        @DataTable AS DT
        INNER JOIN DetermineActionTypeCTE AS DACT WITH(NOLOCK)
        ON
			(DACT.PKID = DT.PKID);

    /** CREATE THE AUDIT ACTIONS */
    DECLARE @AuditActionTable TABLE (AuditActionID BIGINT,
        PKID VARCHAR(50));
    INSERT INTO [AUD].[AuditActions]
        ([AuditActionTypeId], [SchemaName], [TableName], [PrimaryKeyIdentifier], [CreatedById])
    OUTPUT INSERTED.AuditActionID, INSERTED.PrimaryKeyIdentifier INTO @AuditActionTable
    SELECT DISTINCT
        DT.AuditActionTypeId
		, 'QAL'
		, 'LeadAddresses'
		, CAST(DT.PKID AS VARCHAR(50))
		, @UserID
    FROM
        @DataTable AS DT;

    /** CREATE THE AUDIT ACTION COLUMNS */
    INSERT INTO [AUD].[AuditActionColumns]
        ([AuditActionId], [ColumnName], [OldValue], [NewValue])
    SELECT DISTINCT
        AAT.AuditActionID
		, DT.ColumnName
		, DT.OldValue
		, DT.NewValue
    FROM
        @DataTable AS DT
        INNER JOIN @AuditActionTable AS AAT
        ON
			(AAT.PKID = DT.PKID)
END;
GO
