DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserRecruitCohabbitTypes_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserRecruitCohabbitTypes_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserRecruitCohabbitTypes]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserRecruitCohabbitTypes_UPDATE]
(
		@UserRecruitCohabbitTypeID INT		
		, @UserRecruitCohabbitTypeName NVARCHAR(50)		
		, @Rent MONEY		
		, @Pet MONEY		
		, @Utilities MONEY		
		, @GasDeduction MONEY		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitCohabbitTypes') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitCohabbitTypes') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserRecruitCohabbitTypes]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserRecruitCohabbitTypes SET
		[UserRecruitCohabbitTypeName] = @UserRecruitCohabbitTypeName
		, [Rent] = @Rent
		, [Pet] = @Pet
		, [Utilities] = @Utilities
		, [GasDeduction] = @GasDeduction
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(UserRecruitCohabbitTypeID = @UserRecruitCohabbitTypeID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserRecruitCohabbitTypes
	 WHERE
		(UserRecruitCohabbitTypeID = @UserRecruitCohabbitTypeID);

END;

GO
