DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_SeasonSummerSeasonMaps_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_SeasonSummerSeasonMaps_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[SeasonSummerSeasonMaps]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_SeasonSummerSeasonMaps_UPDATE]
(
		@SeasonSummerID INT		
		, @SeasonID INT
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','SeasonSummerSeasonMaps') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','SeasonSummerSeasonMaps') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[SeasonSummerSeasonMaps]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.SeasonSummerSeasonMaps SET
		[SeasonID] = @SeasonID
	 WHERE
		(SeasonSummerID = @SeasonSummerID)
		AND (SeasonID = @SeasonID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.SeasonSummerSeasonMaps
	 WHERE
		(SeasonSummerID = @SeasonSummerID)
		AND (SeasonID = @SeasonID);

END;

GO
