DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_TeamLocationRosters_CREATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_TeamLocationRosters_CREATE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[TeamLocationRosters]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_TeamLocationRosters_CREATE]
(
		@TeamLocationId INT
		, @TerminationReasonId INT
		, @UserRecruitId INT
		, @ArrivalDate DATE
		, @QuitDate DATE
		, @Reason NVARCHAR(MAX)
		, @TerminationType NVARCHAR(50)
		, @Note NVARCHAR(MAX)
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @TeamLocationRosterID INT
		, @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

		/**********************************
		 * SET Modified And Created By IDs
		 **********************************/
		IF (@ModifiedById IS NULL OR @ModifiedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @ModifiedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
		IF (@CreatedById IS NULL OR @CreatedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @CreatedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('CREATE','RSU','TeamLocationRosters') AS AL WHERE (AL.CreateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.CreateAccessId  FROM [GEN].fxGetAccessLevel('CREATE','RSU','TeamLocationRosters') AS AL WHERE (AL.CreateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR ('[50100]:The user "%s" does not have CREATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[TeamLocationRosters]');

		RETURN;
	 END

	 /************
	 * CREATE ROW
	 ************/
	 INSERT INTO RSU.TeamLocationRosters (
		[TeamLocationId]
		, [TerminationReasonId]
		, [UserRecruitId]
		, [ArrivalDate]
		, [QuitDate]
		, [Reason]
		, [TerminationType]
		, [Note]
		, [IsActive]
		, [ModifiedById]
		, [CreatedById]
	 )VALUES (
		@TeamLocationId
		, @TerminationReasonId
		, @UserRecruitId
		, @ArrivalDate
		, @QuitDate
		, @Reason
		, @TerminationType
		, @Note
		, @IsActive
		, @ModifiedById
		, @CreatedById
	 );

	 /*************
	 * Return ROW
	 **************/
	 SELECT * FROM RSU.TeamLocationRosters
		WHERE
		(TeamLocationRosterID = SCOPE_IDENTITY());

END;

GO
