DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserRecruitSeasonGoals_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserRecruitSeasonGoals_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserRecruitSeasonGoals]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserRecruitSeasonGoals_UPDATE]
(
		@UserRecruitSeasonGoalID INT		
		, @UserRecruitId INT		
		, @TotalInstalls FLOAT		
		, @CancelPercent FLOAT		
		, @SubPercent FLOAT		
		, @PassPercent FLOAT		
		, @PastDuePercent FLOAT		
		, @BackendHoldPercent FLOAT		
		, @ActivationWaivePercent FLOAT		
		, @CommercialPercent FLOAT		
		, @PointBank FLOAT		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitSeasonGoals') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitSeasonGoals') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserRecruitSeasonGoals]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserRecruitSeasonGoals SET
		[UserRecruitId] = @UserRecruitId
		, [TotalInstalls] = @TotalInstalls
		, [CancelPercent] = @CancelPercent
		, [SubPercent] = @SubPercent
		, [PassPercent] = @PassPercent
		, [PastDuePercent] = @PastDuePercent
		, [BackendHoldPercent] = @BackendHoldPercent
		, [ActivationWaivePercent] = @ActivationWaivePercent
		, [CommercialPercent] = @CommercialPercent
		, [PointBank] = @PointBank
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(UserRecruitSeasonGoalID = @UserRecruitSeasonGoalID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserRecruitSeasonGoals
	 WHERE
		(UserRecruitSeasonGoalID = @UserRecruitSeasonGoalID);

END;

GO
