DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_TeamLocationRosters_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_TeamLocationRosters_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[TeamLocationRosters]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_TeamLocationRosters_UPDATE]
(
		@TeamLocationRosterID INT		
		, @TeamLocationId INT		
		, @TerminationReasonId INT		
		, @UserRecruitId INT		
		, @ArrivalDate DATE		
		, @QuitDate DATE		
		, @Reason NVARCHAR(MAX)		
		, @TerminationType NVARCHAR(50)		
		, @Note NVARCHAR(MAX)		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','TeamLocationRosters') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','TeamLocationRosters') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[TeamLocationRosters]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.TeamLocationRosters SET
		[TeamLocationId] = @TeamLocationId
		, [TerminationReasonId] = @TerminationReasonId
		, [UserRecruitId] = @UserRecruitId
		, [ArrivalDate] = @ArrivalDate
		, [QuitDate] = @QuitDate
		, [Reason] = @Reason
		, [TerminationType] = @TerminationType
		, [Note] = @Note
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(TeamLocationRosterID = @TeamLocationRosterID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.TeamLocationRosters
	 WHERE
		(TeamLocationRosterID = @TeamLocationRosterID);

END;

GO
