DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserResources_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserResources_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserResources]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserResources_UPDATE]
	(
	@UserResourceID INT
		,
	@DealerId INT
		,
	@UserId UNIQUEIDENTIFIER
		,
	@UserEmployeeTypeId VARCHAR(20)
		,
	@UserResourceAddressId INT
		,
	@RecruitedById INT
		,
	@GPEmployeeId NVARCHAR(25)
		,
	@RecruitedByDate DATETIMEOFFSET
		,
	@FullName NVARCHAR(101)
		,
	@PublicFullName NVARCHAR(53)
		,
	@SSN NVARCHAR(50)
		,
	@FirstName NVARCHAR(50)
		,
	@MiddleName NVARCHAR(50)
		,
	@LastName NVARCHAR(50)
		,
	@PreferredName NVARCHAR(50)
		,
	@CompanyName NVARCHAR(50)
		,
	@MaritalStatus BIT
		,
	@SpouseName NVARCHAR(50)
		,
	@UserName NVARCHAR(256)
		,
	@Password VARCHAR(60)
		,
	@BirthDate DATETIME
		,
	@HomeTown NVARCHAR(50)
		,
	@BirthCity NVARCHAR(50)
		,
	@BirthState NVARCHAR(50)
		,
	@BirthCountry NVARCHAR(50)
		,
	@Sex TINYINT
		,
	@ShirtSize TINYINT
		,
	@HatSize TINYINT
		,
	@DLNumber NVARCHAR(50)
		,
	@DLState NVARCHAR(50)
		,
	@DLCountry NVARCHAR(50)
		,
	@DLExpiresOn DATETIME
		,
	@DLExpiration NVARCHAR(50)
		,
	@Height NVARCHAR(10)
		,
	@Weight NVARCHAR(10)
		,
	@EyeColor NVARCHAR(20)
		,
	@HairColor NVARCHAR(20)
		,
	@PhoneHome NVARCHAR(25)
		,
	@PhoneCell NVARCHAR(50)
		,
	@PhoneCellCarrierID SMALLINT
		,
	@PhoneFax NVARCHAR(25)
		,
	@Email NVARCHAR(100)
		,
	@CorporateEmail NVARCHAR(100)
		,
	@TreeLevel INT
		,
	@HasVerifiedAddress BIT
		,
	@RightToWorkExpirationDate DATETIME
		,
	@RightToWorkNotes NVARCHAR(250)
		,
	@RightToWorkStatusID INT
		,
	@IsLocked BIT
		,
	@IsActive BIT
		,
	@ModifiedDate DATETIMEOFFSET
		,
	@ModifiedById UNIQUEIDENTIFIER
		,
	@CreatedDate DATETIMEOFFSET
		,
	@CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	IF (NOT EXISTS(SELECT *
	FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserResources') AS AL
	WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserResources') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1
			@UserGUID = UserGuidIDMasked
		FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserResources]');
		RETURN;
	END

	/************
	 * UPDATE ROW
	 ************/
	UPDATE RSU.UserResources SET
		[DealerTenantId] = @DealerId
		, [UserId] = @UserId
		, [UserEmployeeTypeId] = @UserEmployeeTypeId
		, [UserResourceAddressId] = @UserResourceAddressId
		, [RecruitedById] = @RecruitedById
		, [GPEmployeeId] = @GPEmployeeId
		, [RecruitedByDate] = @RecruitedByDate
		, [FullName] = @FullName
		, [PublicFullName] = @PublicFullName
		, [SSN] = @SSN
		, [FirstName] = @FirstName
		, [MiddleName] = @MiddleName
		, [LastName] = @LastName
		, [PreferredName] = @PreferredName
		, [CompanyName] = @CompanyName
		, [MaritalStatus] = @MaritalStatus
		, [SpouseName] = @SpouseName
		, [UserName] = @UserName
		, [Password] = @Password
		, [BirthDate] = @BirthDate
		, [HomeTown] = @HomeTown
		, [BirthCity] = @BirthCity
		, [BirthState] = @BirthState
		, [BirthCountry] = @BirthCountry
		, [Sex] = @Sex
		, [ShirtSize] = @ShirtSize
		, [HatSize] = @HatSize
		, [DLNumber] = @DLNumber
		, [DLState] = @DLState
		, [DLCountry] = @DLCountry
		, [DLExpiresOn] = @DLExpiresOn
		, [DLExpiration] = @DLExpiration
		, [Height] = @Height
		, [Weight] = @Weight
		, [EyeColor] = @EyeColor
		, [HairColor] = @HairColor
		, [PhoneHome] = @PhoneHome
		, [PhoneCell] = @PhoneCell
		, [PhoneCellCarrierID] = @PhoneCellCarrierID
		, [PhoneFax] = @PhoneFax
		, [Email] = @Email
		, [CorporateEmail] = @CorporateEmail
		, [TreeLevel] = @TreeLevel
		, [HasVerifiedAddress] = @HasVerifiedAddress
		, [RightToWorkExpirationDate] = @RightToWorkExpirationDate
		, [RightToWorkNotes] = @RightToWorkNotes
		, [RightToWorkStatusID] = @RightToWorkStatusID
		, [IsLocked] = @IsLocked
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(UserResourceID = @UserResourceID);

	/**************
	 * RETURN ROW
	 **************/
	SELECT *
	FROM RSU.UserResources
	WHERE
		(UserResourceID = @UserResourceID);

END;

GO
