DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserAuthentication_CREATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserAuthentication_CREATE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[UserAuthentication]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserAuthentication_CREATE]
(
		@UserResourceId INT
		, @TokenId UNIQUEIDENTIFIER
		, @Username NVARCHAR(50)
		, @Password NVARCHAR(50)
		, @IPAddress VARCHAR(16)
		, @Successfull BIT
		, @Message VARCHAR(150)
		, @IsActive BIT
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @UserAuthenticationID BIGINT
		, @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

		/**********************************
		 * SET Modified And Created By IDs
		 **********************************/
		IF (@CreatedById IS NULL OR @CreatedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @CreatedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
		IF (@ModifiedById IS NULL OR @ModifiedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @ModifiedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('CREATE','RSU','UserAuthentication') AS AL WHERE (AL.CreateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.CreateAccessId  FROM [GEN].fxGetAccessLevel('CREATE','RSU','UserAuthentication') AS AL WHERE (AL.CreateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR ('[50100]:The user "%s" does not have CREATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserAuthentication]');

		RETURN;
	 END

	 /************
	 * CREATE ROW
	 ************/
	 INSERT INTO RSU.UserAuthentication (
		[UserResourceId]
		, [TokenId]
		, [Username]
		, [Password]
		, [IPAddress]
		, [Successfull]
		, [Message]
		, [IsActive]
		, [CreatedById]
		, [ModifiedById]
	 )VALUES (
		@UserResourceId
		, @TokenId
		, @Username
		, @Password
		, @IPAddress
		, @Successfull
		, @Message
		, @IsActive
		, @CreatedById
		, @ModifiedById
	 );

	 /*************
	 * Return ROW
	 **************/
	 SELECT * FROM RSU.UserAuthentication
		WHERE
		(UserAuthenticationID = SCOPE_IDENTITY());

END;

GO
