DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserRecruits_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserRecruits_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserRecruits]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserRecruits_UPDATE]
(
		@UserRecruitID INT		
		, @UserResourceId INT		
		, @UserTypeId SMALLINT		
		, @ReportsToId INT		
		, @UserRecruitAddressId INT		
		, @DealerId INT		
		, @SeasonId INT		
		, @OwnerApprovalId INT		
		, @TeamId INT		
		, @PayScaleId INT		
		, @SchoolId SMALLINT		
		, @ShackingUpId INT		
		, @UserRecruitCohabbitTypeId INT		
		, @AlternatePayScheduleId INT		
		, @Location NVARCHAR(50)		
		, @OwnerApprovalDate DATETIMEOFFSET		
		, @ManagerApprovalDate DATETIMEOFFSET		
		, @EmergencyName NVARCHAR(50)		
		, @EmergencyPhone VARCHAR(20)		
		, @EmergencyRelationship NVARCHAR(50)		
		, @IsRecruiter BIT		
		, @PreviousSummer NVARCHAR(200)		
		, @SignatureDate DATETIMEOFFSET		
		, @HireDate DATETIMEOFFSET		
		, @GPExemptions INT		
		, @GPW4Allowances TINYINT		
		, @GPW9Name NVARCHAR(50)		
		, @GPW9BusinessName NVARCHAR(100)		
		, @GPW9TIN VARCHAR(50)		
		, @SocialSecCardStatusID INT		
		, @DriversLicenseStatusID INT		
		, @W4StatusID INT		
		, @I9StatusID INT		
		, @W9StatusID INT		
		, @SocialSecCardNotes NVARCHAR(250)		
		, @DriversLicenseNotes NVARCHAR(250)		
		, @W4Notes NVARCHAR(250)		
		, @I9Notes NVARCHAR(250)		
		, @W9Notes NVARCHAR(250)		
		, @EIN NVARCHAR(50)		
		, @SUTA NVARCHAR(50)		
		, @WorkersComp NVARCHAR(MAX)		
		, @FedFilingStatus NVARCHAR(50)		
		, @EICFilingStatus NVARCHAR(50)		
		, @TaxWitholdingState NVARCHAR(5)		
		, @StateFilingStatus NVARCHAR(50)		
		, @GPDependents INT		
		, @CriminalOffense BIT		
		, @Offense NVARCHAR(MAX)		
		, @OffenseExplanation NVARCHAR(MAX)		
		, @Rent MONEY		
		, @Pet MONEY		
		, @Utilities MONEY		
		, @Fuel MONEY		
		, @Furniture MONEY		
		, @CellPhoneCredit MONEY		
		, @GasCredit MONEY		
		, @RentExempt BIT		
		, @IsServiceTech BIT		
		, @StateId VARCHAR(4)		
		, @CountryId NVARCHAR(10)		
		, @StreetAddress NVARCHAR(50)		
		, @StreetAddress2 NVARCHAR(50)		
		, @City NVARCHAR(50)		
		, @PostalCode NVARCHAR(10)		
		, @CBxSocialSecCard BIT		
		, @CBxDriversLicense BIT		
		, @CBxW4 BIT		
		, @CBxI9 BIT		
		, @CBxW9 BIT		
		, @PersonalMultiple INT		
		, @IsActive BIT		
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruits') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruits') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserRecruits]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserRecruits SET
		[UserResourceId] = @UserResourceId
		, [UserTypeId] = @UserTypeId
		, [ReportsToId] = @ReportsToId
		, [UserRecruitAddressId] = @UserRecruitAddressId
		, [DealerId] = @DealerId
		, [SeasonId] = @SeasonId
		, [OwnerApprovalId] = @OwnerApprovalId
		, [TeamId] = @TeamId
		, [PayScaleId] = @PayScaleId
		, [SchoolId] = @SchoolId
		, [ShackingUpId] = @ShackingUpId
		, [UserRecruitCohabbitTypeId] = @UserRecruitCohabbitTypeId
		, [AlternatePayScheduleId] = @AlternatePayScheduleId
		, [Location] = @Location
		, [OwnerApprovalDate] = @OwnerApprovalDate
		, [ManagerApprovalDate] = @ManagerApprovalDate
		, [EmergencyName] = @EmergencyName
		, [EmergencyPhone] = @EmergencyPhone
		, [EmergencyRelationship] = @EmergencyRelationship
		, [IsRecruiter] = @IsRecruiter
		, [PreviousSummer] = @PreviousSummer
		, [SignatureDate] = @SignatureDate
		, [HireDate] = @HireDate
		, [GPExemptions] = @GPExemptions
		, [GPW4Allowances] = @GPW4Allowances
		, [GPW9Name] = @GPW9Name
		, [GPW9BusinessName] = @GPW9BusinessName
		, [GPW9TIN] = @GPW9TIN
		, [SocialSecCardStatusID] = @SocialSecCardStatusID
		, [DriversLicenseStatusID] = @DriversLicenseStatusID
		, [W4StatusID] = @W4StatusID
		, [I9StatusID] = @I9StatusID
		, [W9StatusID] = @W9StatusID
		, [SocialSecCardNotes] = @SocialSecCardNotes
		, [DriversLicenseNotes] = @DriversLicenseNotes
		, [W4Notes] = @W4Notes
		, [I9Notes] = @I9Notes
		, [W9Notes] = @W9Notes
		, [EIN] = @EIN
		, [SUTA] = @SUTA
		, [WorkersComp] = @WorkersComp
		, [FedFilingStatus] = @FedFilingStatus
		, [EICFilingStatus] = @EICFilingStatus
		, [TaxWitholdingState] = @TaxWitholdingState
		, [StateFilingStatus] = @StateFilingStatus
		, [GPDependents] = @GPDependents
		, [CriminalOffense] = @CriminalOffense
		, [Offense] = @Offense
		, [OffenseExplanation] = @OffenseExplanation
		, [Rent] = @Rent
		, [Pet] = @Pet
		, [Utilities] = @Utilities
		, [Fuel] = @Fuel
		, [Furniture] = @Furniture
		, [CellPhoneCredit] = @CellPhoneCredit
		, [GasCredit] = @GasCredit
		, [RentExempt] = @RentExempt
		, [IsServiceTech] = @IsServiceTech
		, [StateId] = @StateId
		, [CountryId] = @CountryId
		, [StreetAddress] = @StreetAddress
		, [StreetAddress2] = @StreetAddress2
		, [City] = @City
		, [PostalCode] = @PostalCode
		, [CBxSocialSecCard] = @CBxSocialSecCard
		, [CBxDriversLicense] = @CBxDriversLicense
		, [CBxW4] = @CBxW4
		, [CBxI9] = @CBxI9
		, [CBxW9] = @CBxW9
		, [PersonalMultiple] = @PersonalMultiple
		, [IsActive] = @IsActive
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
		, [ModifiedDate] = SYSDATETIMEOFFSET()
	 WHERE
		(UserRecruitID = @UserRecruitID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserRecruits
	 WHERE
		(UserRecruitID = @UserRecruitID);

END;

GO
