DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserResourceImages_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserResourceImages_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserResourceImages]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserResourceImages_UPDATE]
(
		@UserResourceImageID INT		
		, @UserResourceId INT		
		, @ImageTypeId VARCHAR(20)		
		, @Size INT		
		, @FileName NVARCHAR(500)		
		, @Image NVARCHAR(MAX)		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserResourceImages') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserResourceImages') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserResourceImages]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserResourceImages SET
		[UserResourceId] = @UserResourceId
		, [ImageTypeId] = @ImageTypeId
		, [Size] = @Size
		, [FileName] = @FileName
		, [Image] = @Image
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(UserResourceImageID = @UserResourceImageID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserResourceImages
	 WHERE
		(UserResourceImageID = @UserResourceImageID);

END;

GO
