DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_SiteCodes_CREATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_SiteCodes_CREATE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[SiteCodes]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_SiteCodes_CREATE]
(
		@PoliticalStateId VARCHAR(4)
		, @SiteCodeValue NVARCHAR(50)
		, @SiteCodeDescription NVARCHAR(255)
		, @IsDefault BIT
		, @IsActive BIT
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @SiteCodeID INT
		, @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

		/**********************************
		 * SET Modified And Created By IDs
		 **********************************/
		IF (@CreatedById IS NULL OR @CreatedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @CreatedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
		IF (@ModifiedById IS NULL OR @ModifiedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @ModifiedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('CREATE','RSU','SiteCodes') AS AL WHERE (AL.CreateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.CreateAccessId  FROM [GEN].fxGetAccessLevel('CREATE','RSU','SiteCodes') AS AL WHERE (AL.CreateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR ('[50100]:The user "%s" does not have CREATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[SiteCodes]');

		RETURN;
	 END

	 /************
	 * CREATE ROW
	 ************/
	 INSERT INTO RSU.SiteCodes (
		[PoliticalStateId]
		, [SiteCodeValue]
		, [SiteCodeDescription]
		, [IsDefault]
		, [IsActive]
		, [CreatedById]
		, [ModifiedById]
	 )VALUES (
		@PoliticalStateId
		, @SiteCodeValue
		, @SiteCodeDescription
		, @IsDefault
		, @IsActive
		, @CreatedById
		, @ModifiedById
	 );

	 /*************
	 * Return ROW
	 **************/
	 SELECT * FROM RSU.SiteCodes
		WHERE
		(SiteCodeID = SCOPE_IDENTITY());

END;

GO
