DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_SiteCodes_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_SiteCodes_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[SiteCodes]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_SiteCodes_UPDATE]
(
		@SiteCodeID INT		
		, @PoliticalStateId VARCHAR(4)		
		, @SiteCodeValue NVARCHAR(50)		
		, @SiteCodeDescription NVARCHAR(255)		
		, @IsDefault BIT		
		, @IsActive BIT		
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','SiteCodes') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','SiteCodes') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[SiteCodes]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.SiteCodes SET
		[PoliticalStateId] = @PoliticalStateId
		, [SiteCodeValue] = @SiteCodeValue
		, [SiteCodeDescription] = @SiteCodeDescription
		, [IsDefault] = @IsDefault
		, [IsActive] = @IsActive
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
		, [ModifiedDate] = SYSDATETIMEOFFSET()
	 WHERE
		(SiteCodeID = @SiteCodeID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.SiteCodes
	 WHERE
		(SiteCodeID = @SiteCodeID);

END;

GO
