DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserTypes_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserTypes_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserTypes]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserTypes_UPDATE]
(
		@UserTypeID SMALLINT		
		, @UserTypeTeamTypeId INT		
		, @UserTypeGroupId VARCHAR(20)		
		, @UserTypeName VARCHAR(30)		
		, @SecurityLevel TINYINT		
		, @SpawnTypeId INT		
		, @RoleLocationId INT		
		, @ReportingLevel INT		
		, @IsCommissionable BIT		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserTypes') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserTypes') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserTypes]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserTypes SET
		[UserTypeTeamTypeId] = @UserTypeTeamTypeId
		, [UserTypeGroupId] = @UserTypeGroupId
		, [UserTypeName] = @UserTypeName
		, [SecurityLevel] = @SecurityLevel
		, [SpawnTypeId] = @SpawnTypeId
		, [RoleLocationId] = @RoleLocationId
		, [ReportingLevel] = @ReportingLevel
		, [IsCommissionable] = @IsCommissionable
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(UserTypeID = @UserTypeID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserTypes
	 WHERE
		(UserTypeID = @UserTypeID);

END;

GO
