DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_TerminationCategories_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_TerminationCategories_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[TerminationCategories]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_TerminationCategories_UPDATE]
(
		@TerminationCategoryID INT		
		, @TerminationTypeId INT		
		, @TerminationCategoryName NVARCHAR(50)		
		, @RequiresLastDateWorked BIT		
		, @RequiresExplanation BIT		
		, @RequiresNoticeGiven BIT		
		, @RequiresIntendedLastDay BIT		
		, @RequiresNewTeamLocationId BIT		
		, @ExplanationPrompt NVARCHAR(MAX)		
		, @IsActive BIT		
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','TerminationCategories') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','TerminationCategories') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[TerminationCategories]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.TerminationCategories SET
		[TerminationTypeId] = @TerminationTypeId
		, [TerminationCategoryName] = @TerminationCategoryName
		, [RequiresLastDateWorked] = @RequiresLastDateWorked
		, [RequiresExplanation] = @RequiresExplanation
		, [RequiresNoticeGiven] = @RequiresNoticeGiven
		, [RequiresIntendedLastDay] = @RequiresIntendedLastDay
		, [RequiresNewTeamLocationId] = @RequiresNewTeamLocationId
		, [ExplanationPrompt] = @ExplanationPrompt
		, [IsActive] = @IsActive
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
		, [ModifiedDate] = SYSDATETIMEOFFSET()
	 WHERE
		(TerminationCategoryID = @TerminationCategoryID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.TerminationCategories
	 WHERE
		(TerminationCategoryID = @TerminationCategoryID);

END;

GO
