DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserRecruitAddresses_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserRecruitAddresses_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserRecruitAddresses]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserRecruitAddresses_UPDATE]
(
		@UserRecruitAddressID INT		
		, @PoliticalStateId VARCHAR(4)		
		, @PoliticalCountryId NVARCHAR(10)		
		, @PoliticalTimeZoneId INT		
		, @StreetAddress NVARCHAR(50)		
		, @StreetAddress2 NVARCHAR(50)		
		, @City NVARCHAR(50)		
		, @PostalCode NVARCHAR(10)		
		, @PlusFour NVARCHAR(4)		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitAddresses') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitAddresses') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserRecruitAddresses]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserRecruitAddresses SET
		[PoliticalStateId] = @PoliticalStateId
		, [PoliticalCountryId] = @PoliticalCountryId
		, [PoliticalTimeZoneId] = @PoliticalTimeZoneId
		, [StreetAddress] = @StreetAddress
		, [StreetAddress2] = @StreetAddress2
		, [City] = @City
		, [PostalCode] = @PostalCode
		, [PlusFour] = @PlusFour
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(UserRecruitAddressID = @UserRecruitAddressID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserRecruitAddresses
	 WHERE
		(UserRecruitAddressID = @UserRecruitAddressID);

END;

GO
