DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserRecruitRegistrations_CREATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserRecruitRegistrations_CREATE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[UserRecruitRegistrations]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserRecruitRegistrations_CREATE]
(
		@UniqueRegistrationId UNIQUEIDENTIFIER
		, @InvitedByUserResourceId INT
		, @ExistingUserResourceId INT
		, @RegistrationDate DATETIME
		, @RecruitedByUserResourceId INT
		, @UserRecruitAddressId INT
		, @SSN NVARCHAR(50)
		, @FirstName NVARCHAR(50)
		, @MiddleName NVARCHAR(50)
		, @LastName NVARCHAR(50)
		, @PreferredName NVARCHAR(50)
		, @FullName NVARCHAR(101)
		, @UserName NVARCHAR(50)
		, @BirthDate DATETIME
		, @BirthCity NVARCHAR(50)
		, @BirthState NVARCHAR(50)
		, @BirthCountry NVARCHAR(50)
		, @Sex TINYINT
		, @ShirtSize TINYINT
		, @HatSize TINYINT
		, @DLNumber NVARCHAR(50)
		, @DLState NVARCHAR(50)
		, @DLCountry NVARCHAR(50)
		, @DLExpiration NVARCHAR(50)
		, @Height NVARCHAR(10)
		, @Weight NVARCHAR(10)
		, @EyeColor NVARCHAR(20)
		, @HairColor NVARCHAR(20)
		, @PhoneHome NVARCHAR(25)
		, @PhoneCell NVARCHAR(50)
		, @PhoneCellCarrierID SMALLINT
		, @Email NVARCHAR(100)
		, @UserTypeId SMALLINT
		, @ReportsToID INT
		, @CurrentAddressID INT
		, @PayScaleID INT
		, @SchoolId SMALLINT
		, @HasPet BIT
		, @NeedsExtraHousing BIT
		, @EmergencyName NVARCHAR(50)
		, @EmergencyPhone VARCHAR(20)
		, @EmergencyRelationship NVARCHAR(50)
		, @PreviousSummer NVARCHAR(200)
		, @CriminalOffense BIT
		, @Offense NVARCHAR(MAX)
		, @OffenseExplanation NVARCHAR(MAX)
		, @StartDate DATETIME
		, @StartingState NVARCHAR(50)
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @UserRecruitRegistrationID INT
		, @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

		/**********************************
		 * SET Modified And Created By IDs
		 **********************************/
		IF (@ModifiedById IS NULL OR @ModifiedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @ModifiedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
		IF (@CreatedById IS NULL OR @CreatedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @CreatedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('CREATE','RSU','UserRecruitRegistrations') AS AL WHERE (AL.CreateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.CreateAccessId  FROM [GEN].fxGetAccessLevel('CREATE','RSU','UserRecruitRegistrations') AS AL WHERE (AL.CreateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR ('[50100]:The user "%s" does not have CREATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserRecruitRegistrations]');

		RETURN;
	 END

	 /************
	 * CREATE ROW
	 ************/
	 INSERT INTO RSU.UserRecruitRegistrations (
		[UniqueRegistrationId]
		, [InvitedByUserResourceId]
		, [ExistingUserResourceId]
		, [RegistrationDate]
		, [RecruitedByUserResourceId]
		, [UserRecruitAddressId]
		, [SSN]
		, [FirstName]
		, [MiddleName]
		, [LastName]
		, [PreferredName]
		, [FullName]
		, [UserName]
		, [BirthDate]
		, [BirthCity]
		, [BirthState]
		, [BirthCountry]
		, [Sex]
		, [ShirtSize]
		, [HatSize]
		, [DLNumber]
		, [DLState]
		, [DLCountry]
		, [DLExpiration]
		, [Height]
		, [Weight]
		, [EyeColor]
		, [HairColor]
		, [PhoneHome]
		, [PhoneCell]
		, [PhoneCellCarrierID]
		, [Email]
		, [UserTypeId]
		, [ReportsToID]
		, [CurrentAddressID]
		, [PayScaleID]
		, [SchoolId]
		, [HasPet]
		, [NeedsExtraHousing]
		, [EmergencyName]
		, [EmergencyPhone]
		, [EmergencyRelationship]
		, [PreviousSummer]
		, [CriminalOffense]
		, [Offense]
		, [OffenseExplanation]
		, [StartDate]
		, [StartingState]
		, [IsActive]
		, [ModifiedById]
		, [CreatedById]
	 )VALUES (
		@UniqueRegistrationId
		, @InvitedByUserResourceId
		, @ExistingUserResourceId
		, @RegistrationDate
		, @RecruitedByUserResourceId
		, @UserRecruitAddressId
		, @SSN
		, @FirstName
		, @MiddleName
		, @LastName
		, @PreferredName
		, @FullName
		, @UserName
		, @BirthDate
		, @BirthCity
		, @BirthState
		, @BirthCountry
		, @Sex
		, @ShirtSize
		, @HatSize
		, @DLNumber
		, @DLState
		, @DLCountry
		, @DLExpiration
		, @Height
		, @Weight
		, @EyeColor
		, @HairColor
		, @PhoneHome
		, @PhoneCell
		, @PhoneCellCarrierID
		, @Email
		, @UserTypeId
		, @ReportsToID
		, @CurrentAddressID
		, @PayScaleID
		, @SchoolId
		, @HasPet
		, @NeedsExtraHousing
		, @EmergencyName
		, @EmergencyPhone
		, @EmergencyRelationship
		, @PreviousSummer
		, @CriminalOffense
		, @Offense
		, @OffenseExplanation
		, @StartDate
		, @StartingState
		, @IsActive
		, @ModifiedById
		, @CreatedById
	 );

	 /*************
	 * Return ROW
	 **************/
	 SELECT * FROM RSU.UserRecruitRegistrations
		WHERE
		(UserRecruitRegistrationID = SCOPE_IDENTITY());

END;

GO
