DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserPhotos_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserPhotos_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserPhotos]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserPhotos_UPDATE]
(
		@UserPhotoID INT		
		, @UserResourceId INT		
		, @PhotoImage NVARCHAR(MAX)		
		, @FileSize BIGINT		
		, @MimeType NVARCHAR(100)		
		, @IsActive BIT		
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserPhotos') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserPhotos') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserPhotos]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserPhotos SET
		[UserResourceId] = @UserResourceId
		, [PhotoImage] = @PhotoImage
		, [FileSize] = @FileSize
		, [MimeType] = @MimeType
		, [IsActive] = @IsActive
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
		, [ModifiedDate] = SYSDATETIMEOFFSET()
	 WHERE
		(UserPhotoID = @UserPhotoID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserPhotos
	 WHERE
		(UserPhotoID = @UserPhotoID);

END;

GO
