DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_Teams_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_Teams_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[Teams]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_Teams_UPDATE]
(
		@TeamID INT		
		, @Description VARCHAR(50)		
		, @CreatedFromTeamId INT		
		, @TeamLocationId INT		
		, @RoleLocationId INT		
		, @RegionalManagerRecruitId INT		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','Teams') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','Teams') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[Teams]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.Teams SET
		[Description] = @Description
		, [CreatedFromTeamId] = @CreatedFromTeamId
		, [TeamLocationId] = @TeamLocationId
		, [RoleLocationId] = @RoleLocationId
		, [RegionalManagerRecruitId] = @RegionalManagerRecruitId
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(TeamID = @TeamID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.Teams
	 WHERE
		(TeamID = @TeamID);

END;

GO
