DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_SeasonSummerSeasonMaps_CREATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_SeasonSummerSeasonMaps_CREATE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[SeasonSummerSeasonMaps]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_SeasonSummerSeasonMaps_CREATE]
(
		
		@SeasonSummerID INT
		, @SeasonID INT
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('CREATE','RSU','SeasonSummerSeasonMaps') AS AL WHERE (AL.CreateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.CreateAccessId  FROM [GEN].fxGetAccessLevel('CREATE','RSU','SeasonSummerSeasonMaps') AS AL WHERE (AL.CreateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR ('[50100]:The user "%s" does not have CREATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[SeasonSummerSeasonMaps]');

		RETURN;
	 END

	 /************
	 * CREATE ROW
	 ************/
	 INSERT INTO RSU.SeasonSummerSeasonMaps (
		[SeasonSummerID]
		, [SeasonID]
	 )VALUES (
		@SeasonSummerID
		, @SeasonID
	 );

	 /*************
	 * Return ROW
	 **************/
	 SELECT * FROM RSU.SeasonSummerSeasonMaps
		WHERE
		(SeasonSummerID = @SeasonSummerID)
		AND (SeasonID = @SeasonID);

END;

GO
