DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_Terminations_CREATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_Terminations_CREATE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[Terminations]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_Terminations_CREATE]
(
		@UserRecruitId INT
		, @TerminationCategoryId INT
		, @TeamLocationId INT
		, @LastDateWorked DATETIME
		, @Explanation NVARCHAR(MAX)
		, @NoticeGiven BIT
		, @IntendedLastDay DATETIME
		, @IsActive BIT
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @TerminationID INT
		, @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

		/**********************************
		 * SET Modified And Created By IDs
		 **********************************/
		IF (@CreatedById IS NULL OR @CreatedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @CreatedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
		IF (@ModifiedById IS NULL OR @ModifiedById = '00000000-0000-0000-0000-000000000000') BEGIN
			SET @ModifiedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
		END 
	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('CREATE','RSU','Terminations') AS AL WHERE (AL.CreateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.CreateAccessId  FROM [GEN].fxGetAccessLevel('CREATE','RSU','Terminations') AS AL WHERE (AL.CreateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR ('[50100]:The user "%s" does not have CREATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[Terminations]');

		RETURN;
	 END

	 /************
	 * CREATE ROW
	 ************/
	 INSERT INTO RSU.Terminations (
		[UserRecruitId]
		, [TerminationCategoryId]
		, [TeamLocationId]
		, [LastDateWorked]
		, [Explanation]
		, [NoticeGiven]
		, [IntendedLastDay]
		, [IsActive]
		, [CreatedById]
		, [ModifiedById]
	 )VALUES (
		@UserRecruitId
		, @TerminationCategoryId
		, @TeamLocationId
		, @LastDateWorked
		, @Explanation
		, @NoticeGiven
		, @IntendedLastDay
		, @IsActive
		, @CreatedById
		, @ModifiedById
	 );

	 /*************
	 * Return ROW
	 **************/
	 SELECT * FROM RSU.Terminations
		WHERE
		(TerminationID = SCOPE_IDENTITY());

END;

GO
