DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_Terminations_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_Terminations_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[Terminations]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_Terminations_UPDATE]
(
		@TerminationID INT		
		, @UserRecruitId INT		
		, @TerminationCategoryId INT		
		, @TeamLocationId INT		
		, @LastDateWorked DATETIME		
		, @Explanation NVARCHAR(MAX)		
		, @NoticeGiven BIT		
		, @IntendedLastDay DATETIME		
		, @IsActive BIT		
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','Terminations') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','Terminations') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[Terminations]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.Terminations SET
		[UserRecruitId] = @UserRecruitId
		, [TerminationCategoryId] = @TerminationCategoryId
		, [TeamLocationId] = @TeamLocationId
		, [LastDateWorked] = @LastDateWorked
		, [Explanation] = @Explanation
		, [NoticeGiven] = @NoticeGiven
		, [IntendedLastDay] = @IntendedLastDay
		, [IsActive] = @IsActive
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
		, [ModifiedDate] = SYSDATETIMEOFFSET()
	 WHERE
		(TerminationID = @TerminationID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.Terminations
	 WHERE
		(TerminationID = @TerminationID);

END;

GO
