DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserAuthentication_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserAuthentication_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserAuthentication]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserAuthentication_UPDATE]
(
		@UserAuthenticationID BIGINT		
		, @UserResourceId INT		
		, @TokenId UNIQUEIDENTIFIER		
		, @Username NVARCHAR(50)		
		, @Password NVARCHAR(50)		
		, @IPAddress VARCHAR(16)		
		, @Successfull BIT		
		, @Message VARCHAR(150)		
		, @IsActive BIT		
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserAuthentication') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserAuthentication') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserAuthentication]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserAuthentication SET
		[UserResourceId] = @UserResourceId
		, [TokenId] = @TokenId
		, [Username] = @Username
		, [Password] = @Password
		, [IPAddress] = @IPAddress
		, [Successfull] = @Successfull
		, [Message] = @Message
		, [IsActive] = @IsActive
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
		, [ModifiedDate] = SYSDATETIMEOFFSET()
	 WHERE
		(UserAuthenticationID = @UserAuthenticationID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserAuthentication
	 WHERE
		(UserAuthenticationID = @UserAuthenticationID);

END;

GO
