DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserRecruitRegistrations_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserRecruitRegistrations_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[UserRecruitRegistrations]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserRecruitRegistrations_UPDATE]
(
		@UserRecruitRegistrationID INT		
		, @UniqueRegistrationId UNIQUEIDENTIFIER		
		, @InvitedByUserResourceId INT		
		, @ExistingUserResourceId INT		
		, @RegistrationDate DATETIME		
		, @RecruitedByUserResourceId INT		
		, @UserRecruitAddressId INT		
		, @SSN NVARCHAR(50)		
		, @FirstName NVARCHAR(50)		
		, @MiddleName NVARCHAR(50)		
		, @LastName NVARCHAR(50)		
		, @PreferredName NVARCHAR(50)		
		, @FullName NVARCHAR(101)		
		, @UserName NVARCHAR(50)		
		, @BirthDate DATETIME		
		, @BirthCity NVARCHAR(50)		
		, @BirthState NVARCHAR(50)		
		, @BirthCountry NVARCHAR(50)		
		, @Sex TINYINT		
		, @ShirtSize TINYINT		
		, @HatSize TINYINT		
		, @DLNumber NVARCHAR(50)		
		, @DLState NVARCHAR(50)		
		, @DLCountry NVARCHAR(50)		
		, @DLExpiration NVARCHAR(50)		
		, @Height NVARCHAR(10)		
		, @Weight NVARCHAR(10)		
		, @EyeColor NVARCHAR(20)		
		, @HairColor NVARCHAR(20)		
		, @PhoneHome NVARCHAR(25)		
		, @PhoneCell NVARCHAR(50)		
		, @PhoneCellCarrierID SMALLINT		
		, @Email NVARCHAR(100)		
		, @UserTypeId SMALLINT		
		, @ReportsToID INT		
		, @CurrentAddressID INT		
		, @PayScaleID INT		
		, @SchoolId SMALLINT		
		, @HasPet BIT		
		, @NeedsExtraHousing BIT		
		, @EmergencyName NVARCHAR(50)		
		, @EmergencyPhone VARCHAR(20)		
		, @EmergencyRelationship NVARCHAR(50)		
		, @PreviousSummer NVARCHAR(200)		
		, @CriminalOffense BIT		
		, @Offense NVARCHAR(MAX)		
		, @OffenseExplanation NVARCHAR(MAX)		
		, @StartDate DATETIME		
		, @StartingState NVARCHAR(50)		
		, @IsActive BIT		
		, @ModifiedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitRegistrations') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','UserRecruitRegistrations') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserRecruitRegistrations]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserRecruitRegistrations SET
		[UniqueRegistrationId] = @UniqueRegistrationId
		, [InvitedByUserResourceId] = @InvitedByUserResourceId
		, [ExistingUserResourceId] = @ExistingUserResourceId
		, [RegistrationDate] = @RegistrationDate
		, [RecruitedByUserResourceId] = @RecruitedByUserResourceId
		, [UserRecruitAddressId] = @UserRecruitAddressId
		, [SSN] = @SSN
		, [FirstName] = @FirstName
		, [MiddleName] = @MiddleName
		, [LastName] = @LastName
		, [PreferredName] = @PreferredName
		, [FullName] = @FullName
		, [UserName] = @UserName
		, [BirthDate] = @BirthDate
		, [BirthCity] = @BirthCity
		, [BirthState] = @BirthState
		, [BirthCountry] = @BirthCountry
		, [Sex] = @Sex
		, [ShirtSize] = @ShirtSize
		, [HatSize] = @HatSize
		, [DLNumber] = @DLNumber
		, [DLState] = @DLState
		, [DLCountry] = @DLCountry
		, [DLExpiration] = @DLExpiration
		, [Height] = @Height
		, [Weight] = @Weight
		, [EyeColor] = @EyeColor
		, [HairColor] = @HairColor
		, [PhoneHome] = @PhoneHome
		, [PhoneCell] = @PhoneCell
		, [PhoneCellCarrierID] = @PhoneCellCarrierID
		, [Email] = @Email
		, [UserTypeId] = @UserTypeId
		, [ReportsToID] = @ReportsToID
		, [CurrentAddressID] = @CurrentAddressID
		, [PayScaleID] = @PayScaleID
		, [SchoolId] = @SchoolId
		, [HasPet] = @HasPet
		, [NeedsExtraHousing] = @NeedsExtraHousing
		, [EmergencyName] = @EmergencyName
		, [EmergencyPhone] = @EmergencyPhone
		, [EmergencyRelationship] = @EmergencyRelationship
		, [PreviousSummer] = @PreviousSummer
		, [CriminalOffense] = @CriminalOffense
		, [Offense] = @Offense
		, [OffenseExplanation] = @OffenseExplanation
		, [StartDate] = @StartDate
		, [StartingState] = @StartingState
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(UserRecruitRegistrationID = @UserRecruitRegistrationID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserRecruitRegistrations
	 WHERE
		(UserRecruitRegistrationID = @UserRecruitRegistrationID);

END;

GO
