DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_UserRecruitRegistrations_DELETE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_UserRecruitRegistrations_DELETE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[UserRecruitRegistrations]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_UserRecruitRegistrations_DELETE]
(
	@UserRecruitRegistrationID int
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('DELETE','RSU','UserRecruitRegistrations') AS AL WHERE (AL.DeleteAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('DELETE','RSU','UserRecruitRegistrations') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50130]|The user "%s" does not have DELETE privileges on table "%s".'
           , 11 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[UserRecruitRegistrations]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.UserRecruitRegistrations SET
		IsDeleted = 1
		, ModifiedDate = SYSDATETIMEOFFSET()
		, ModifiedById = @ACLUserID
	 
	 WHERE
		(UserRecruitRegistrationID = @UserRecruitRegistrationID);


	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.UserRecruitRegistrations
	 WHERE
		(UserRecruitRegistrationID = @UserRecruitRegistrationID);

END;

GO
