DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_Seasons_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_Seasons_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[Seasons]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_Seasons_UPDATE]
	(
	@SeasonID INT
		,
	@PreSeasonID INT
		,
	@DealerId INT
		,
	@SeasonName NVARCHAR(50)
		,
	@StartDate DATETIMEOFFSET
		,
	@EndDate DATETIMEOFFSET
		,
	@ShowInHiringManager BIT
		,
	@IsCurrent BIT
		,
	@IsVisibleToRecruits BIT
		,
	@IsInsideSales BIT
		,
	@IsPreseason BIT
		,
	@IsSummer BIT
		,
	@IsExtended BIT
		,
	@IsYearRound BIT
		,
	@IsContractor BIT
		,
	@IsDealer BIT
		,
	@IsCurbNSign BIT
		,
	@ExcellentCreditScoreThreshold INT
		,
	@PassCreditScoreThreshold INT
		,
	@SubCreditScoreThreshold INT
		,
	@IsActive BIT
		,
	@ModifiedDate DATETIMEOFFSET
		,
	@ModifiedById UNIQUEIDENTIFIER
		,
	@CreatedDate DATETIMEOFFSET
		,
	@CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	IF (NOT EXISTS(SELECT *
	FROM [GEN].fxGetAccessLevel('UPDATE','RSU','Seasons') AS AL
	WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','Seasons') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1
			@UserGUID = UserGuidIDMasked
		FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[Seasons]');
		RETURN;
	END

	/************
	 * UPDATE ROW
	 ************/
	UPDATE RSU.Seasons SET
		[PreSeasonID] = @PreSeasonID
		, [DealerTenantId] = @DealerId
		, [SeasonName] = @SeasonName
		, [StartDate] = @StartDate
		, [EndDate] = @EndDate
		, [ShowInHiringManager] = @ShowInHiringManager
		, [IsCurrent] = @IsCurrent
		, [IsVisibleToRecruits] = @IsVisibleToRecruits
		, [IsInsideSales] = @IsInsideSales
		, [IsPreseason] = @IsPreseason
		, [IsSummer] = @IsSummer
		, [IsExtended] = @IsExtended
		, [IsYearRound] = @IsYearRound
		, [IsContractor] = @IsContractor
		, [IsDealer] = @IsDealer
		, [IsCurbNSign] = @IsCurbNSign
		, [ExcellentCreditScoreThreshold] = @ExcellentCreditScoreThreshold
		, [PassCreditScoreThreshold] = @PassCreditScoreThreshold
		, [SubCreditScoreThreshold] = @SubCreditScoreThreshold
		, [IsActive] = @IsActive
		, [ModifiedDate] = SYSDATETIMEOFFSET()
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
	 WHERE
		(SeasonID = @SeasonID);

	/**************
	 * RETURN ROW
	 **************/
	SELECT *
	FROM RSU.Seasons
	WHERE
		(SeasonID = @SeasonID);

END;

GO
