DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_TerminationNotes_UPDATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_TerminationNotes_UPDATE]
**		Desc: Autogenerated SPROC to UPDATE a row for [RSU].[TerminationNotes]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_TerminationNotes_UPDATE]
(
		@TerminationNoteID INT		
		, @TerminationId INT		
		, @NoteText NVARCHAR(MAX)		
		, @IsActive BIT		
		, @CreatedById UNIQUEIDENTIFIER		
		, @CreatedDate DATETIMEOFFSET		
		, @ModifiedById UNIQUEIDENTIFIER		
		, @ModifiedDate DATETIMEOFFSET
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	 DECLARE @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	 IF (NOT EXISTS(SELECT * FROM [GEN].fxGetAccessLevel('UPDATE','RSU','TerminationNotes') AS AL WHERE (AL.UpdateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.UpdateAccessId  FROM [GEN].fxGetAccessLevel('UPDATE','RSU','TerminationNotes') AS AL WHERE (AL.UpdateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1 @UserGUID = UserGuidIDMasked FROM [GEN].fxGetUserInfo();

		RAISERROR (N'[50120]|The user "%s" does not have UPDATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[TerminationNotes]');
		RETURN;
	 END

	 /************
	 * UPDATE ROW
	 ************/
	 UPDATE RSU.TerminationNotes SET
		[TerminationId] = @TerminationId
		, [NoteText] = @NoteText
		, [IsActive] = @IsActive
		, [ModifiedById] = UTL.fxGetDefaultGuidId(@ModifiedById)
		, [ModifiedDate] = SYSDATETIMEOFFSET()
	 WHERE
		(TerminationNoteID = @TerminationNoteID);

	 /**************
	 * RETURN ROW
	 **************/
	 SELECT * FROM RSU.TerminationNotes
	 WHERE
		(TerminationNoteID = @TerminationNoteID);

END;

GO
