DROP PROCEDURE IF EXISTS [RSU].[spAutoGen_Seasons_CREATE];
GO


/**********************************************************************************************************************
**		Name: [RSU].[spAutoGen_Seasons_CREATE]
**		Desc: Autogenerated SPROC to CREATE a row for [RSU].[Seasons]
**		Auth: ANDRES E. SOSA
**		Date: 10/02/2015 (UTC)
***********************************************************************************************************************/
CREATE   Procedure [RSU].[spAutoGen_Seasons_CREATE]
	(
	@PreSeasonID INT
		,
	@DealerId INT
		,
	@SeasonName NVARCHAR(50)
		,
	@StartDate DATETIMEOFFSET
		,
	@EndDate DATETIMEOFFSET
		,
	@ShowInHiringManager BIT
		,
	@IsCurrent BIT
		,
	@IsVisibleToRecruits BIT
		,
	@IsInsideSales BIT
		,
	@IsPreseason BIT
		,
	@IsSummer BIT
		,
	@IsExtended BIT
		,
	@IsYearRound BIT
		,
	@IsContractor BIT
		,
	@IsDealer BIT
		,
	@IsCurbNSign BIT
		,
	@ExcellentCreditScoreThreshold INT
		,
	@PassCreditScoreThreshold INT
		,
	@SubCreditScoreThreshold INT
		,
	@IsActive BIT
		,
	@ModifiedDate DATETIMEOFFSET
		,
	@ModifiedById UNIQUEIDENTIFIER
		,
	@CreatedDate DATETIMEOFFSET
		,
	@CreatedById UNIQUEIDENTIFIER
)
AS
BEGIN
	/**************
	 * INITIALIZE
	 **************/
	DECLARE @SeasonID INT
		, @ACLUserID UNIQUEIDENTIFIER = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER)
		, @UserGUID NVARCHAR(MAX)
		, @CreatedAccessId SMALLINT;

	/**********************************
		 * SET Modified And Created By IDs
		 **********************************/
	IF (@ModifiedById IS NULL OR @ModifiedById = '00000000-0000-0000-0000-000000000000') BEGIN
		SET @ModifiedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
	END
	IF (@CreatedById IS NULL OR @CreatedById = '00000000-0000-0000-0000-000000000000') BEGIN
		SET @CreatedById = CAST(CONTEXT_INFO() AS UNIQUEIDENTIFIER);
	END
	/*********************
	 * CHECK ACCESS LEVEL
	 *********************/
	IF (NOT EXISTS(SELECT *
	FROM [GEN].fxGetAccessLevel('CREATE','RSU','Seasons') AS AL
	WHERE (AL.CreateAccessId > 0))) BEGIN
		--** Get ACL Information
		--SELECT @ACLUserID = UserId, @UserGUID = @UserGUID, @CreatedAccessId = AL.CreateAccessId  FROM [GEN].fxGetAccessLevel('CREATE','RSU','Seasons') AS AL WHERE (AL.CreateAccessId > 0)

		--** Check that there is a user
		SELECT TOP 1
			@UserGUID = UserGuidIDMasked
		FROM [GEN].fxGetUserInfo();

		RAISERROR ('[50100]:The user "%s" does not have CREATE privileges on table "%s".'
           , 18 -- Severity,
           , 1 -- State,
           , @UserGUID
		   , N'[RSU].[Seasons]');

		RETURN;
	END

	/************
	 * CREATE ROW
	 ************/
	INSERT INTO RSU.Seasons
		(
		[PreSeasonID]
		, [DealerTenantId]
		, [SeasonName]
		, [StartDate]
		, [EndDate]
		, [ShowInHiringManager]
		, [IsCurrent]
		, [IsVisibleToRecruits]
		, [IsInsideSales]
		, [IsPreseason]
		, [IsSummer]
		, [IsExtended]
		, [IsYearRound]
		, [IsContractor]
		, [IsDealer]
		, [IsCurbNSign]
		, [ExcellentCreditScoreThreshold]
		, [PassCreditScoreThreshold]
		, [SubCreditScoreThreshold]
		, [IsActive]
		, [ModifiedById]
		, [CreatedById]
		)
	VALUES
		(
			@PreSeasonID
		, @DealerId
		, @SeasonName
		, @StartDate
		, @EndDate
		, @ShowInHiringManager
		, @IsCurrent
		, @IsVisibleToRecruits
		, @IsInsideSales
		, @IsPreseason
		, @IsSummer
		, @IsExtended
		, @IsYearRound
		, @IsContractor
		, @IsDealer
		, @IsCurbNSign
		, @ExcellentCreditScoreThreshold
		, @PassCreditScoreThreshold
		, @SubCreditScoreThreshold
		, @IsActive
		, @ModifiedById
		, @CreatedById
	 );

	/*************
	 * Return ROW
	 **************/
	SELECT *
	FROM RSU.Seasons
	WHERE
		(SeasonID = SCOPE_IDENTITY());

END;

GO
