/******************************************************************************
**		File: fxGeneratePrefixParts.sql
**		Name: fxGeneratePrefixParts
**		Desc: Table-valued function that returns a single row containing the
**            Proxy-ID parts (Prefix, PartKey) for a given TypeName and TypeId.
**
**            The Prefix is looked up from the appropriate *Types table.
**            The PartKey is generated by calling UTL.fxGetPartKey() which
**            returns the hex-encoded current year+month.
**
**            MAINTENANCE: Every time a new Proxy-enabled entity type is created,
**            add an ELSE IF block here AND update MAC.vwTableTypesAndPrefixes
**            AND register the prefix in .github/ProxyID-PrefixRegistry.md.
**
**		Return values: TABLE (Prefix VARCHAR(4), PartKey VARCHAR(6))
**
**		Called by: MAC.fxGeneratePrefixProxy
**
**		Parameters:
**		Input							Output
**     ----------					-----------
**      @TypeName  VARCHAR(50)      Prefix VARCHAR(4)
**      @TypeId    INT              PartKey VARCHAR(6)
**
**		Auth: Andres E. Sosa
**		Date: 2026-05-05
*******************************************************************************
**	Change History
*******************************************************************************
**	Date:		Author:				Description:
**	-----------	---------------		-------------------------------------------
**	2026-05-05	Andres E. Sosa		Created By
**
*******************************************************************************/

DROP FUNCTION IF EXISTS [MAC].[fxGeneratePrefixParts];
GO

CREATE FUNCTION [MAC].[fxGeneratePrefixParts] (
    @TypeName  VARCHAR(50)
    , @TypeId  INT
)
RETURNS @Parts TABLE (
    Prefix VARCHAR(4),
    PartKey VARCHAR(6)
)
AS
BEGIN
    DECLARE @Prefix VARCHAR(4);

    -- =========================================================================
    -- DealerTenant — ACC.DealerTenantTypes
    -- =========================================================================
    IF (@TypeName = 'DealerTenant')
    BEGIN
        SELECT @Prefix = [Prefix]
        FROM [ACC].[DealerTenantTypes] AS T WITH (NOLOCK)
        WHERE (T.[DealerTenantTypeID] = @TypeId);
    END

    -- =========================================================================
    -- ADD NEW ELSE IF BLOCKS BELOW as new Proxy-enabled entities are onboarded.
    -- Follow the checklist in .github/ProxyID-PrefixRegistry.md.
    -- =========================================================================

    -- Insert result row only if a prefix was resolved
    IF (@Prefix IS NOT NULL)
    BEGIN
        INSERT INTO @Parts
            ([Prefix], [PartKey])
        VALUES
            (@Prefix, [UTL].[fxGetPartKey]());
    END

    RETURN;
END
GO
